apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../karpenter
- ../../monitoring
patches:
- path: replica-ai-gateway.yaml
- path: replica-inference-api.yaml
labels:
- pairs:
    vanguard.ai/env: dev
  includeSelectors: false
